name: Repro

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - test-1024

jobs:
  repro:
    name: 'Repro: node permissions error'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: cp cli/package.json package.json
      - run: cp cli/package-lock.json package-lock.json
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: cli/go.sum
          go-version-file: go.work
      - name: Setup Node (prism)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.tool-versions'
      - run: npm install
